package mtc::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'mtc::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:root/database',
        user => '',
        password => '',
    }
);

sub get_customer_for_select {
    my ($self) = @_;
    
    my $customer = $self->resultset('Customer');
    my $value_label = [];    
    if($customer->count > 0) {
        while(my $row = $customer->next) {
            my $name = $row->firstname." ".$row->lastname;
            push(@{$value_label}, { value => $row->cid, label => $name });
        }
    }
    return $value_label;
}

=head1 NAME

mtc::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<mtc>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<mtc::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
